mongodb:
  MONGO_DB_USERNAME: "admin"
  MONGO_DB_PASSWORD: "secret"

kafka:
  servers:
    - localhost:9092
  group: accountConsumer
  groupline: linenoti

line:
  LINE_CHANNEL_SECRET: ""
  LINE_CHANNEL_TOKEN: ""